# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    brochures_directory: '%kernel.project_dir%/public/uploads/'
    amazon.s3.key: '%env(S3_ACCESS_KEY_ID)%'
    amazon.s3.secret: '%env(S3_SECRET_ACCESS_KEY)%'
    amazon.s3.bucket: '%env(S3_BUCKET_NAME)%'
    amazon.s3.region: '%env(S3_BUCKET_REGION)%'
    amazon.s3.version: "latest"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\AuthenticationFailureListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    App\EventListener\JWTInvalidListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

    App\Services\UploadImageService:
        arguments:
            $targetDirectory: '%brochures_directory%'
    App\Manager\FileManager:
        arguments:
            $key: '%amazon.s3.key%'
            $secret: '%amazon.s3.secret%'
            $bucket: '%amazon.s3.bucket%'
            $region: '%amazon.s3.region%'
            $version: '%amazon.s3.version%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
